/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covid19;

import Helper.MessageDialog;
import Profile.Profile;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class StatisticDebtFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewDebtFrame
     */
    public StatisticDebtFrame() {
        initComponents();
        displayData();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSDebt = new javax.swing.JPanel();
        scrollpnlSDebt = new javax.swing.JScrollPane();
        tblSDebt = new javax.swing.JTable();
        lblSDebt = new javax.swing.JLabel();
        pnlBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnViewTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistic Debt Table");
        setMaximumSize(new java.awt.Dimension(1200, 650));

        tblSDebt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Debt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpnlSDebt.setViewportView(tblSDebt);
        if (tblSDebt.getColumnModel().getColumnCount() > 0) {
            tblSDebt.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblSDebt.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblSDebt.getColumnModel().getColumn(2).setPreferredWidth(25);
        }

        lblSDebt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSDebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/statisics-48.png"))); // NOI18N
        lblSDebt.setText("Statistic Debt Table:");

        javax.swing.GroupLayout pnlSDebtLayout = new javax.swing.GroupLayout(pnlSDebt);
        pnlSDebt.setLayout(pnlSDebtLayout);
        pnlSDebtLayout.setHorizontalGroup(
            pnlSDebtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSDebtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSDebtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollpnlSDebt, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSDebtLayout.setVerticalGroup(
            pnlSDebtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSDebtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpnlSDebt, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view.png"))); // NOI18N
        btnViewTotal.setText("View Total");
        btnViewTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnViewTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTotalActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tblSDebt.getModel();
            int rows = tblSDebt.getRowCount();
            double total = 0;
            for (int i = 0; i < rows; i++) {
//            total +=  Float.parseFloat((String) model.getValueAt(i, 4));
                total += (double) model.getValueAt(i, 2);
            }

            StaticsTotal staticsTotal = new StaticsTotal(String.valueOf(total));
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, "Can't view total. Something was wrong!!", "Error!");
//            e.printStackTrace();
        }
    }//GEN-LAST:event_btnViewTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new StatisticDebtFrame().setVisible(true);
        });
    }

    private void displayData() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblSDebt.getModel();
            model.setRowCount(0);

            List<Profile> lst = Patient.PatientInf.getAllPatient();
            for (Profile profile : lst) {
                if (profile.getDebt() > 0 ) {
                    Object[] obj = {profile.getID(), profile.getFullName(), profile.getDebt()};
                    model.addRow(obj);
                }
            }

        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewTotal;
    private javax.swing.JLabel lblSDebt;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlSDebt;
    private javax.swing.JScrollPane scrollpnlSDebt;
    private javax.swing.JTable tblSDebt;
    // End of variables declaration//GEN-END:variables
}
